In [ ]:
Ok!s/content/drive/MyDrive/ALKASHAN

/bin/bash: line 1: s/content/drive/MyDrive/ALKASHAN: No such file or directory


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#!7za -y x "/content/drive/MyDrive/DSAI_Prj-1/data/image/origin.7z.*"

In [ ]:
#!cp -r ./origin "/content/drive/MyDrive/DSAI_Prj-1"

cp: cannot stat './origin': No such file or directory


In [42]:
label_file_path=r"/content/drive/MyDrive/DSAI_Prj-1/data/label/label.lst"
images_folder_path=r"/content/drive/MyDrive/DSAI_Prj-1/origin"

In [43]:
from numpy import split
import pandas as pd
df_info = pd.read_csv(label_file_path, sep=" ",header=None)
col_names="image_name face_id_in_image face_box_top face_box_left face_box_right face_box_bottom face_box_confidence expression_label".split()
df_info.columns = col_names

df_info.head()

image_name  face_id_in_image  face_box_top  face_box_left  \
0  angry_actor_104.jpg                 0            28            113   
1  angry_actor_109.jpg                 0            31            157   
2  angry_actor_120.jpg                 1            53             53   
3   angry_actor_13.jpg                 0            77             51   
4  angry_actor_132.jpg                 0            95             31   

   face_box_right  face_box_bottom  face_box_confidence  expression_label  
0             226              141              22.9362                 0  
1             345              219              50.3056                 0  
2             372              372              13.9434                 2  
3             362              388              85.8104                 3  
4             412              476              82.3948                 0

In [44]:
df_info.shape

(91793, 8)

In [86]:
df_sel=df_info[df_info.face_box_confidence>45]

In [87]:
df_sel

image_name  face_id_in_image  face_box_top  \
1                 angry_actor_109.jpg                 0            31   
3                  angry_actor_13.jpg                 0            77   
4                 angry_actor_132.jpg                 0            95   
5                 angry_actor_137.jpg                 0            93   
9                 angry_actor_150.jpg                 0            56   
...                               ...               ...           ...   
91786    surprised_expression_409.jpg                 0            80   
91787  expressionless_husband_673.jpg                 0            48   
91789    surprised_expression_381.jpg                 0            51   
91790    surprised_expression_395.jpg                 0            27   
91792    surprised_expression_394.jpg                 0            47   

       face_box_left  face_box_right  face_box_bottom  face_box_confidence  \
1                157             345              219              50.3056   
3                 51             362              388              85.8104   
4                 31             412              476              82.3948   
5                468             842              467              88.9519   
9                263             376              169              81.8792   
...              ...             ...              ...                  ...   
91786             46             184              218              63.8069   
91787            194             388              242              82.2975   
91789             61             117              107              91.6307   
91790             95             258              190              96.2861   
91792             38             152              161              77.7758   

       expression_label  
1                     0  
3                     3  
4                     0  
5                     0  
9                     0  
...                 ...  
91786                 5  
91787                 4  
91789                 5  
91790                 5  
91792                 5  

[51856 rows x 8 columns]

In [88]:
df_sel.image_name.value_counts()

awe_teacher_108.jpg              112
astound_expression_526.jpg        52
awe_grandfather_256.jpg           50
astound_expression_400.jpg        48
amazed_president_890.jpg          46
                                ... 
expressionless_wife_880.jpg        1
expressionless_woman_139.jpg       1
expressionless_worker_310.jpg      1
expressionless_worker_328.jpg      1
surprised_expression_394.jpg       1
Name: image_name, Length: 40628, dtype: int64

In [89]:
df_sel.shape

(51856, 8)

In [90]:
import cv2
import os
x=[]
y=[]
for i, row in df_sel.iterrows():
  img_name=row["image_name"]
  x1 = row["face_box_left"]
  y1=row["face_box_top"]
  x2=row["face_box_right"]
  y2=row["face_box_bottom"]
  label=row["expression_label"]
  img_path=os.path.join(images_folder_path,img_name)

  image = cv2.imread(img_path)

  #croping
  if image is not None:
        cropped=image[y1:y2, x1:x2]
        face = cv2.resize(cropped, (48, 48))
        if face is not None:
          x.append(face)
          y.append(label)


In [91]:
import numpy as np
X = np.array(x)
Y = np.array(y)

In [92]:
X

array([[[[ 30,  46,  59],
         [ 33,  47,  61],
         [ 40,  51,  65],
         ...,
         [ 92, 100, 114],
         [ 96, 104, 117],
         [ 62,  71,  81]],

        [[ 28,  41,  55],
         [ 27,  38,  52],
         [ 51,  61,  75],
         ...,
         [ 87,  94, 110],
         [ 90,  97, 112],
         [100, 108, 121]],

        [[ 34,  45,  59],
         [ 30,  40,  54],
         [ 66,  75,  89],
         ...,
         [ 87,  94, 111],
         [ 95, 102, 119],
         [ 93, 100, 115]],

        ...,

        [[ 85,  91, 122],
         [ 86,  92, 122],
         [ 86,  93, 120],
         ...,
         [ 31,  47,  64],
         [ 44,  60,  77],
         [ 44,  60,  77]],

        [[ 84,  89, 120],
         [ 86,  91, 121],
         [ 89,  96, 123],
         ...,
         [ 30,  46,  63],
         [ 38,  54,  71],
         [ 35,  51,  69]],

        [[ 90,  95, 126],
         [ 87,  93, 122],
         [ 84,  91, 118],
         ...,
         [ 37,  53,  70],
        

In [93]:
Y

array([1, 3, 3, ..., 1, 6, 6])

In [94]:
len(X)

1657

In [95]:
len(Y)

1657

In [96]:
X.shape

(1657, 48, 48, 3)

In [97]:
Y.shape

(1657,)

In [98]:
normalized_X = X / 255.0

In [99]:
normalized_X

array([[[[0.11764706, 0.18039216, 0.23137255],
         [0.12941176, 0.18431373, 0.23921569],
         [0.15686275, 0.2       , 0.25490196],
         ...,
         [0.36078431, 0.39215686, 0.44705882],
         [0.37647059, 0.40784314, 0.45882353],
         [0.24313725, 0.27843137, 0.31764706]],

        [[0.10980392, 0.16078431, 0.21568627],
         [0.10588235, 0.14901961, 0.20392157],
         [0.2       , 0.23921569, 0.29411765],
         ...,
         [0.34117647, 0.36862745, 0.43137255],
         [0.35294118, 0.38039216, 0.43921569],
         [0.39215686, 0.42352941, 0.4745098 ]],

        [[0.13333333, 0.17647059, 0.23137255],
         [0.11764706, 0.15686275, 0.21176471],
         [0.25882353, 0.29411765, 0.34901961],
         ...,
         [0.34117647, 0.36862745, 0.43529412],
         [0.37254902, 0.4       , 0.46666667],
         [0.36470588, 0.39215686, 0.45098039]],

        ...,

        [[0.33333333, 0.35686275, 0.47843137],
         [0.3372549 , 0.36078431, 0.47843137]

In [100]:
normalized_X.shape

(1657, 48, 48, 3)

In [101]:
X_new=normalized_X.reshape((-1,48*48*3))
X_new.shape

(1657, 6912)

In [102]:
X_new

array([[0.11764706, 0.18039216, 0.23137255, ..., 0.11764706, 0.18039216,
        0.24705882],
       [0.36862745, 0.50196078, 0.49803922, ..., 0.        , 0.        ,
        0.        ],
       [0.21568627, 0.36078431, 0.4627451 , ..., 0.00784314, 0.02352941,
        0.06666667],
       ...,
       [0.99607843, 0.99607843, 0.99607843, ..., 1.        , 1.        ,
        1.        ],
       [0.22745098, 0.23529412, 0.29019608, ..., 0.72941176, 0.4745098 ,
        0.29803922],
       [0.09019608, 0.12156863, 0.23137255, ..., 0.58431373, 0.63137255,
        0.79607843]])

In [103]:
X_new.shape

(1657, 6912)

In [104]:
import pandas as pd
pd.Series(Y).value_counts()

3    816
6    529
5    186
1     57
2     29
4     26
0     14
dtype: int64

In [69]:
X_new.shape

(1692, 13068)

In [105]:
Y.shape

(1657,)

In [106]:
from imblearn.over_sampling import SMOTE
sampler = SMOTE()
X_smote,Y_smote=sampler.fit_resample(X_new, Y)

In [107]:
pd.Series(Y_smote).value_counts()

1    816
3    816
6    816
4    816
0    816
5    816
2    816
dtype: int64

In [109]:
X=X_smote.reshape(-1,48,48,3)

In [110]:
X

array([[[[0.11764706, 0.18039216, 0.23137255],
         [0.12941176, 0.18431373, 0.23921569],
         [0.15686275, 0.2       , 0.25490196],
         ...,
         [0.36078431, 0.39215686, 0.44705882],
         [0.37647059, 0.40784314, 0.45882353],
         [0.24313725, 0.27843137, 0.31764706]],

        [[0.10980392, 0.16078431, 0.21568627],
         [0.10588235, 0.14901961, 0.20392157],
         [0.2       , 0.23921569, 0.29411765],
         ...,
         [0.34117647, 0.36862745, 0.43137255],
         [0.35294118, 0.38039216, 0.43921569],
         [0.39215686, 0.42352941, 0.4745098 ]],

        [[0.13333333, 0.17647059, 0.23137255],
         [0.11764706, 0.15686275, 0.21176471],
         [0.25882353, 0.29411765, 0.34901961],
         ...,
         [0.34117647, 0.36862745, 0.43529412],
         [0.37254902, 0.4       , 0.46666667],
         [0.36470588, 0.39215686, 0.45098039]],

        ...,

        [[0.33333333, 0.35686275, 0.47843137],
         [0.3372549 , 0.36078431, 0.47843137]

In [111]:
import numpy as np
from keras.utils import to_categorical
onehot_encoded_y = to_categorical(Y)

# Display the one-hot encoded representation
print(onehot_encoded_y)


[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [112]:
import numpy as np
from sklearn.model_selection import train_test_split

# Assuming 'x' is your input features and 'y' is the corresponding target labels
# Replace these with your actual data arrays

# Split the data into training (70%), testing (15%), and validation (15%) sets
X_train, X_temp, Y_train, Y_temp = train_test_split(normalized_X, onehot_encoded_y, test_size=0.3, random_state=42)
X_val, X_test, Y_val, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5, random_state=42)

# Display the sizes of each split
print("Training set size:", len(X_train))
print("Validation set size:", len(X_val))
print("Testing set size:", len(X_test))

Training set size: 1159
Validation set size: 249
Testing set size: 249


In [113]:
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

# Assuming 'x_train' is your training data and 'y_train' are the corresponding labels
# Replace these with your actual training data and labels

# Create an ImageDataGenerator for data augmentation
datagen = ImageDataGenerator(
    rotation_range=20,      # Random rotation
    width_shift_range=0.2,  # Random horizontal shift
    height_shift_range=0.2, # Random vertical shift
    shear_range=0.2,        # Random shear
    zoom_range=0.2,         # Random zoom
    horizontal_flip=True,   # Random horizontal flip
    fill_mode='nearest'     # Fill mode for newly created pixels
)

# Fit the ImageDataGenerator on the training data
datagen.fit(X_train)

# Generate augmented data batches
augmented_data_generator = datagen.flow(X_train, Y_train, batch_size=32)



In [114]:
X_train.size

8011008

In [115]:

Y_train.size

8113

In [117]:
import numpy as np
from tensorflow.keras.applications import VGG16
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam



base_model = VGG16(weights='imagenet', include_top=False, input_shape=(48, 48, 3))


for layer in base_model.layers:
    layer.trainable = False


x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)


num_classes = 7

predictions = Dense(num_classes, activation='softmax')(x)


model = Model(inputs=base_model.input, outputs=predictions)


model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])


model.summary()


history = model.fit(X_train, Y_train, batch_size=32, epochs=10, validation_data=(X_val, Y_val))


val_loss, val_accuracy = model.evaluate(X_val, Y_val)

print("Validation Accuracy:", val_accuracy)

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 48, 48, 3)]       0         
                                                                 
 block1_conv1 (Conv2D)       (None, 48, 48, 64)        1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 48, 48, 64)        36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 24, 24, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 24, 24, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 24, 24, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 12, 12, 128)       0   

In [118]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Assuming 'x_train' and 'y_train' are your training data and labels, respectively
# Replace these with your actual training data and labels

# Create the CNN model
model = Sequential()

# Add the first convolutional layer
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(48,48,3)))

# Add the first max-pooling layer
model.add(MaxPooling2D(pool_size=(2, 2)))

# Add the second convolutional layer
model.add(Conv2D(64, (3, 3), activation='relu'))

# Add the second max-pooling layer
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten the output from the previous layer
model.add(Flatten())

# Add the first fully connected (dense) layer
model.add(Dense(128, activation='relu'))

# Add the output layer with appropriate number of classes and activation function
num_classes = 7
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, epochs=200, batch_size=32, validation_data=(X_val, Y_val))


Epoch 1/200
37/37 [==============================] - 2s 19ms/step - loss: 1.3234 - accuracy: 0.4789 - val_loss: 1.2135 - val_accuracy: 0.4940
Epoch 2/200
37/37 [==============================] - 0s 6ms/step - loss: 1.2245 - accuracy: 0.5280 - val_loss: 1.2252 - val_accuracy: 0.4779
Epoch 3/200
37/37 [==============================] - 0s 8ms/step - loss: 1.1594 - accuracy: 0.5315 - val_loss: 1.1597 - val_accuracy: 0.5100
Epoch 4/200
37/37 [==============================] - 0s 7ms/step - loss: 1.0529 - accuracy: 0.6031 - val_loss: 1.1850 - val_accuracy: 0.4900
Epoch 5/200
37/37 [==============================] - 0s 6ms/step - loss: 0.9785 - accuracy: 0.6299 - val_loss: 1.0470 - val_accuracy: 0.5703
Epoch 6/200
37/37 [==============================] - 0s 8ms/step - loss: 0.8952 - accuracy: 0.6730 - val_loss: 1.0882 - val_accuracy: 0.6145
Epoch 7/200
37/37 [==============================] - 0s 10ms/step - loss: 0.8320 - accuracy: 0.6997 - val_loss: 1.0524 - val_accuracy: 0.6265
Epoch 8/200